Fixes Dark Mode Button Failure
sugarlabs/terminal-activity pull request #53
Opened 2024-12-27 09:29 UTC by MostlyKIGuess

### Problem  
The dark mode toggle button in the Terminal activity was non-functional on Ubuntu 24.04. Logs revealed two primary issues:  

1. **Deprecated `readfp` method:**  
   ```python
   AttributeError: 'ConfigParser' object has no attribute 'readfp'. Did you mean: 'read'?
   ```
   The `readfp` method of `ConfigParser` has been deprecated and removed in Python 3, causing `_configure_vt` to fail.

2. **`NoneType` error in `write_file`:**  
   ```python
   AttributeError: 'NoneType' object has no attribute 'split'
   ```
   When writing files, `text` was unexpectedly `None`, causing a crash when attempting to call `split()`.

---

### Solution  

- Replaced the outdated `readfp` method with `read_file` to maintain compatibility with Python 3.  
- Added a null check for `text` to ensure it is not `None` before processing.  
- Improved file handling by using `with` statements for automatic resource management.

---

### Testing  
- Tested the changes in a virtual machine running Ubuntu 24.04.  
- Installed `sucrose` and replaced `/usr/share/sugar/Terminal.activity` with the updated code.  
- Rebooted the system and confirmed that the dark mode toggle now works as expected without errors.  

---

This pull request resolves #51 .

2024-12-28 03:49 UTC, quozl requested changes
Your commits individually didn't make sense, though the overall change did.

* [ ] rearrange the changes into two commits, one for each error reported,
* [ ] use our guidance for writing commit messages, see https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#making-commits

In particular, put in the commit messages a succinct rewrite of what you've put in the pull request opening comment.

2024-12-28 03:49 UTC, quozl commented on terminal.py
> -
Unexpected whitespace change.

2024-12-28 03:49 UTC, quozl commented on terminal.py
> -
And here.

2024-12-28 03:49 UTC, quozl commented on terminal.py
> -
Unexpected whitespace change.

2024-12-28 04:47 UTC, MostlyKIGuess commented on terminal.py
> -
fixed

2024-12-28 04:48 UTC, MostlyKIGuess commented
> Your commits individually didn't make sense, though the overall change did.
> 
>     * [ ]  rearrange the changes into two commits, one for each error reported,
> 
>     * [ ]  use our guidance for writing commit messages, see https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#making-commits
> 
> 
> In particular, put in the commit messages a succinct rewrite of what you've put in the pull request opening comment.

- made it with a single commit itself , added description for more info.

2024-12-28 09:02 UTC, chimosky commented
Not tested, you should take a look at the [sugar-docs](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#contributing) we usually don't open PRs from the master branch.

2024-12-28 20:23 UTC, quozl commented
Tested.  Dark mode toggle works once.  Subsequent button presses or <kbd>ctrl+shift+i</kbd> have no effect.

I began to cherry-pick and split your commit to merge several commits to master by hand, so that unrelated changes are kept separate.  In my experience this helps greatly with `git bisect`, of which I'm a fan.  But I stalled on an ambiguity.

The error in write_file is odd; if text is None then get_text returned it that way.  It should return the text of the terminal.  [Upstream for get_text](https://lazka.github.io/pgi-docs/#Vte-2.91/classes/Terminal.html#Vte.Terminal.get_text) explains why.  I see the gir1.2-vte-291 package is at version 0.76.0-1ubuntu0.1 on my Ubuntu 24.04 test container.  So this is a regression that we should detect and handle.

The upstream description is complex.  I started coding for it and ran out of time.  Yes, we do need to support previous versions of Vte, as a new release of Terminal may be installed on an old release of Sugar and the underlying platform.  Thanks!

2024-12-29 01:52 UTC, MostlyKIGuess commented
> Tested. Dark mode toggle works once. Subsequent button presses or ctrl+shift+i have no effect.
> 
> I began to cherry-pick and split your commit to merge several commits to master by hand, so that unrelated changes are kept separate. In my experience this helps greatly with `git bisect`, of which I'm a fan. But I stalled on an ambiguity.
> 
> The error in write_file is odd; if text is None then get_text returned it that way. It should return the text of the terminal. [Upstream for get_text](https://lazka.github.io/pgi-docs/#Vte-2.91/classes/Terminal.html#Vte.Terminal.get_text) explains why. I see the gir1.2-vte-291 package is at version 0.76.0-1ubuntu0.1 on my Ubuntu 24.04 test container. So this is a regression that we should detect and handle.
> 
> The upstream description is complex. I started coding for it and ran out of time. Yes, we do need to support previous versions of Vte, as a new release of Terminal may be installed on an old release of Sugar and the underlying platform. Thanks!

Are there any logs for it not working post once?
I am not able to recreate the same issue, ctrl+shift+I still works for me. As well as changing color theme.

2024-12-29 03:38 UTC, quozl commented
Same here.  Tested again but with `git checkout ea9715d` rather than `git cherry-pick -n ea9715`.  I've logs of both tests and they are identical apart from timestamps, and nothing to indicate the cause.  Ignore the test failure, as it cannot be reproduced.

2025-01-05 06:21 UTC, MostlyKIGuess reviewed
@quozl  I have made the changes as requested and also rebase. I learnt it !!

2025-01-05 20:47 UTC, quozl commented
Check again in above comments; I've not seen a response to two items.

2025-01-07 10:15 UTC, MostlyKIGuess commented
> Check again in above comments; I've not seen a response to two items.


  - [x]  handle Vte.Terminal.get_text API changes instead of testing for None before split().
  - Added a check for VTE version to handle this.


  - [x]  rearrange the changes into two commits, one for each error reported.
  - as they are on the same file, the previous commit's description explains the error and keeps the message short.

2025-01-07 19:23 UTC, quozl commented on terminal.py
> +            if text:
With the check for VTE_VERSION now present, is this test required?

2025-01-08 03:58 UTC, MostlyKIGuess commented on terminal.py
> +            if text:
For version 36-78 we were doing this thing and it seemed to be working.

2025-01-08 03:58 UTC, MostlyKIGuess commented on terminal.py
> +            if text:
So we can keep it.

2025-01-08 20:39 UTC, quozl commented on terminal.py
> +            if text:
I had said in my previous review;

* [ ] handle Vte.Terminal.get_text API changes instead of testing for None before split().

You've added code to test for None in text.  I'm asking that VTE_VERSION be used instead of that check.

2025-01-09 05:00 UTC, MostlyKIGuess commented on terminal.py
> +            if text:
Ahh, I understand now , I will add and test those changes with different version of vte.

2025-01-09 16:39 UTC, MostlyKIGuess commented on terminal.py
> +            if text:
I have added the changes for this

2025-01-09 20:07 UTC, quozl requested changes
* [ ] split edits into commits by purpose as discussed in chat, thanks.

2025-01-09 20:29 UTC, MostlyKIGuess commented
> * [ ]  split edits into commits by purpose as discussed in chat, thanks.

I hope the new PR works . I shall one day learn how to properly rebase and cherry-pick.

2025-01-10 20:03 UTC, quozl commented
Thanks.  Merged by hand with commit message rewrite.

2025-01-10 20:03 UTC, closed without merging